### PR TITLE
aligning fueltype enum: lowercase, underscore ( due to graphql )

### PR DESCRIPTION
**Pull request by tressko**
[ch-32897]
[skip-ch]

# Summary

### https://github.com/connectedcars/node-vinutils ( npm: "@connectedcars/vinutils")
    breaking changes
        -export function getFuelType(vehicle: any): any
        +export function getFuelType(vehicle: any): FuelType

        -NATURAL_GAS: 'Natural Gas'
        +NATURAL_GAS: 'natural_gas',

### https://github.com/connectedcars/api ( npm: "api")
        ch-32897
        bump @connectedcars/serviceutils
        bump @connectedcars/backend
        bump @connectedcars/vinutils
        bump @connectedcars/integration

### https://github.com/connectedcars/node-integration ( npm: "@connectedcars/integration")
        FuelType input sanitized ( AutoCore.lookupCar )
        bump @connectedcars/vinutils

### https://github.com/connectedcars/node-backend ( npm: "@connectedcars/backend")
        bump @connectedcars/vinutils
        bump @connectedcars/integration

### https://github.com/connectedcars/vehicle-configs ( npm: "@connectedcars/vehicle-configs")
        bump @connectedcars/vinutils

### https://github.com/connectedcars/notifier ( npm: "notifier")
	    Fix fueltype ( and car info )
		bump @connectedcars/backend
		bump @connectedcars/vinutils
		bump @connectedcars/integration

### https://github.com/connectedcars/data ( npm: "@connectedcars/data") DONE
        fix fuelType

## rollout plan
0. data repo ( done )
1. bump major and create v1 branch https://github.com/connectedcars/node-vinutils ( no deps )
2. get vinutils PR's done -> https://github.com/connectedcars/node-vinutils/pull/27
3. bump major and create v1 branches
   - https://github.com/connectedcars/node-integration ( npm: "@connectedcars/integration")
   - https://github.com/connectedcars/node-serviceutils ( npm: "@connectedcars/serviceutils")
      - Deps:
         - @connectedcars/vinutils
4. bump major and create v1 branch
   - https://github.com/connectedcars/node-backend ( npm: "@connectedcars/backend")
      - Deps:
         - @connectedcars/vinutils
         - @connectedcars/integration
5. finish pr's and deploy together
- https://github.com/connectedcars/vehicle-configs ( npm: "@connectedcars/vehicle-configs")
   - Deps:
      - @connectedcars/vinutils
- https://github.com/connectedcars/job-runner-traffilog ( npm: "job-runner-traffilog") ( calls vehicle-config )
- https://github.com/connectedcars/job-runner-rollouts ( npm: "job-runner-rollouts")
   - Deps:
      - @connectedcars/backend
- https://github.com/connectedcars/api ( npm: "api")
   - Deps:
      - @connectedcars/serviceutils
      - @connectedcars/backend
      - @connectedcars/vinutils
      - @connectedcars/integration
- https://github.com/connectedcars/external-lookup ( npm: "external-lookup")
- https://github.com/connectedcars/integration ( npm: "integration")
   - Deps:
      - @connectedcars/backend
      - @connectedcars/integration
        https://github.com/connectedcars/notifier ( npm: "notifier")
   - Deps:
      - @connectedcars/backend
      - @connectedcars/vinutils
      - @connectedcars/integration

6. bump rest of the deptree

        https://github.com/connectedcars/auth-api ( npm: "auth")
        https://github.com/connectedcars/crypto-key-exchange ( npm: "crypto-key-exchange")
        https://github.com/connectedcars/data-mirror ( npm: "data-mirror")
        https://github.com/connectedcars/delta-creator ( npm: "delta-creator")
        https://github.com/connectedcars/delta-creator-v2 ( npm: "delta-creator-v2")
        https://github.com/connectedcars/dmr-parser ( npm: "dmr-parser")
        https://github.com/connectedcars/ingester-onomondo ( npm: "ingester-onomondo")
        https://github.com/connectedcars/job-runner-admin ( npm: "job-runner-admin")
        https://github.com/connectedcars/job-runner-business ( npm: "job-runner-business")
        https://github.com/connectedcars/job-runner-cc-device ( npm: "job-runner-cc-device")
        https://github.com/connectedcars/job-runner-cleanup ( npm: "job-runner-cleanup")
        https://github.com/connectedcars/job-runner-geofence ( npm: "job-runner-geofence")
        https://github.com/connectedcars/job-runner-integration ( npm: "job-runner-integration")
        https://github.com/connectedcars/job-runner-leads ( npm: "job-runner-leads")
        https://github.com/connectedcars/job-runner-reverse-engineering ( npm: "job-runner-reverse-engineering")
        https://github.com/connectedcars/job-runner-stats ( npm: "job-runner-stats")
        https://github.com/connectedcars/job-runner-trips ( npm: "job-runner-trips")
        https://github.com/connectedcars/job-runner-webhooks ( npm: "job-runner-webhooks")
        https://github.com/connectedcars/logger-vcds ( npm: "logger-vcds")
        https://github.com/connectedcars/provisioning-api ( npm: "provisioning-api")
        https://github.com/connectedcars/provisioning-api-v2 ( npm: "provisioning-api-v2")
        https://github.com/connectedcars/pubsub-feeder ( npm: "@connectedcars/pubsub-feeder")
        https://github.com/connectedcars/slack-pubsub ( npm: "slackbot")
            Deps:
                @connectedcars/backend

        https://github.com/connectedcars/ingester-cc-v2 ( npm: "ingester-cc-v2")
            Deps:
                @connectedcars/backend
                @connectedcars/vehicle-configs

        https://github.com/connectedcars/ingester-cc ( npm: "ingester-cc")
            Deps:
                @connectedcars/backend
                @connectedcars/vehicle-configs
                @connectedcars/data

        https://github.com/connectedcars/ingester-tl ( npm: "ingester-tl")
            Deps:
                @connectedcars/backend
                @connectedcars/vehicle-configs
                @connectedcars/vinutils

        https://github.com/connectedcars/feeder ( npm: "feeder")
        https://github.com/connectedcars/ingester ( npm: "ingester")
        https://github.com/connectedcars/ingester-munic ( npm: "ingester-munic")
        https://github.com/connectedcars/mailman ( npm: "mailman")
            Deps:
                @connectedcars/backend
                @connectedcars/vinutils

        https://github.com/connectedcars/reverse-engineering-provider ( npm: "@connectedcars/reverse-engineering-provider")
            Deps:
                @connectedcars/vinutils

7. Nice to have - Introduce Fueltype for `FactoryInfo` and .*TripStatistics, check db & remove enum lowercasing code

### CODE REVIEW

**Comment by tressko** [comment]
looks some integration test fails .. looking into that

**Comment by tressko** [comment]
It fails ( crashes ) the same on master, I don't think this change caused it, @mex want me to look into why the integration test fails or create a ticket?

      ✓ gets model year close to 2015 from WAUZZZ8V1F1123985
      ✓ gets model year close to 2014 from WVWZZZAAZED002951
      1179) gets model year close to 2004 from WP1ZZZ9PZ4LA01779
      ✓ gets model year close to 2018 from WVWZZZAUZJW807985
      ✓ gets model year close to 2018 from TMBJC9NE8J0116052
      ✓ gets model year close to 2013 from WVWZZZAAZDD060090


FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10006d51b node::Abort() [/Users/peter/.nvm/versions/node/v12.0.0/bin/node]
 2: 0x10006dc5c node::errors::TryCatchScope::~TryCatchScope() [/Users/peter/.nvm/versions/node/v12.0.0/bin/node]
 3: 0x100155dc7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/peter/.nvm/versions/node/v12.0.0/bin/node]
 4: 0x100155d5c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/peter/.nvm/versions/node/v12.0.0/bin/node]
 5: 0x100534515 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/peter/.nvm/versions/node/v12.0.0/bin/node]
 6: 0x100535603 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/peter/.nvm/versions/node/v12.0.0/bin/node]
 7: 0x100533003 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/peter/.nvm/versions/node/v12.0.0/bin/node]
 8: 0x100530cbf v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/peter/.nvm/versions/node/v12.0.0/bin/node]

**Comment by mex** [comment]
@tressko Those integration tests are mainly there as a way to sanity check larger changes to the resolver logic for VINs. Don't worry about them here.

**Review by mathiastj — COMMENTED** [review]
As far as I can tell this will require a major version bump of node-vinutils, which in turn willl require a major bump on node-backend and node-integration.

@mex perhaps we'll need to make a rollout plan to make sure we don't mess anything up, while bumping all these projects, and for getting an overview of what needs bumping?

**Comment by tressko** [comment]
@mathiastj @mex maybe also other dependencies? 

update integration(new node-backend, new node-integration)
update notifier(new node-backend, new node-integration, new node-vinutils)
update job-runner-traffilog(new node-backend, new node-vinutils)
update external-lookup(new node-backend, new node-integration

**Comment by mex** [comment]
In addition to those you've listed (including node-integration and node-backend), it is a dependency of:
 - node-serviceutils (your changes are not relevant to the use cases)
 - ingester-tl (your changes are not relevant to the use cases)
 - mailman (your changes are not relevant to the use cases)
 - vehicle-configs

**Comment by mex** [comment]
In each of those projects, you should probably search for `@connectedcars/vinutils`, check what's imported and how it's used to ensure usage of `FuelType` and `getFuelType` can handle the new layout.

**Comment by mathiastj** [comment]
It's also a dependency of the api (of course).

I've been thinking. When we roll this out we need to make sure that `job-runner-rollouts` and `vehicle-configs` is deployed at pretty much exactly the same time. And that `job-runner-rollouts` does not have vinutils/node-backend bumped before we're ready for it.
This is due to the fact that `job-runner-rollouts` calls `vehicle-configs` with fuel type, so if they are not in sync this will be quite critical.

**Comment by tressko** [comment]
@mathiastj @mex please ping me if you have a little time helping me verifying the "rollout plan" :)

**Comment by mathiastj** [comment]
@tressko 
I have a few changes to your rollout plan, let me know what you think (changes in _italics_):

## rollout plan
0. data repo ( done )
~~1. bump major and create v1 branch https://github.com/connectedcars/node-vinutils ( no deps )~~
1. _finish vinutils pr and get it approved_ 
~~2. get vinutils PR's done -> https://github.com/connectedcars/node-vinutils/pull/27~~
2. _just before merging vinutils PR create a v1 branch on the current master and write in #team_backend on slack informing about this!_
2.5 _merge vinutils pr to master, do `npm version major` and upload the major to npm_

Related to 3. and 4.
We'll need to do the same for node-integration, node-serviceutils, and node-backend. That is, finish PR, get it approved. Just before merging create a v1 branch and inform on slack, merge to master and bump major version.
Ideally the PRs to all dependents in step 5 should be as ready to go as possible, before doing the above. So the double work on v1 and master only has to be done for as short a while as possible.

Related to 5.
It won't be necessary to deploy all the changes at the same time. 
The only really important part is that we deploy `vehicle-configs` and `job-runner-rollouts` at the same time. We should probably do this together a day while in the office.
The reason for this is that `job-runner-rollouts` calls `vehicle-configs` and one of the arguments is the fueltype, so if fueltype does not match between the two, then no units will get configs.

As far as I can tell the rest of the projects/repos in your part 5. can be deployed whenever.

Related tot 6.
It's not strictly necessary to bump all these since they don't use fuel type explicitly, but it would be nice to do.
I can see you added `npm: x` to each of them. Most of these projects are not on npm, and should not be. Only the 'libraries' are on npm.

**Review by mathiastj — APPROVED** [review]

**Comment by tressko** [comment]
0-5: Perfectly clear 👍 
6: Yes, got it, and thanks for checking that we are on the same page! This notation "( npm: "feeder")" only refers to the "name" coming from package.json, should have used package-name :)

**Pull request merged**
